Hardware Product Recommender System-kevin -mazhura-h170289y/app/urls.py
"""
Definition of urls for HardwareStore.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import re_path as url
from django.urls.conf import path
from django.urls import include

app_name = 'app'
urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

Hardware Product Recommender System-kevin -mazhura-h170289y/hardreco/urls.py
from django.urls import re_path as url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from shop import views as shop_views

urlpatterns = [
    path('', shop_views.index, name="mainpage"),
    path('auth', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('about/', views.about, name="about"),
    url(r'^shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('profiles/', include('profiles.urls',namespace='profiles')),
    path(r'markdownx/', include('markdownx.urls')),
    path('order/', include('order.urls',namespace='order')),
    path('tfidf/', include('tfidf.urls')),
    path('matrixfactorization/', include('matrixfactorization.urls')),
    url(r'^Scrapper/', include('scrapper.urls',namespace='scrapper')),
    url(r'^app/', include('app.urls')),
]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

Hardware Product Recommender System-kevin -mazhura-h170289y/profiles/urls.py
from . import views
from django.conf.urls import  include
from django.urls import path,re_path as url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'profiles'


urlpatterns = [
    # path('accounts/', include('profiles.accounts.urls', namespace='accounts')),
    path('profiles/<slug:profile_slug>/change-password', views.change_password, name="change-password"),
    path('profiles/<slug:profile_slug>/edit', views.edit_profile, name="edit-profile"),
    path('profiles/<slug:profile_slug>/', views.profile, name="profile"),
    path('intrest/<slug:profile_slug>/', views.add_intrest, name="add_intrest"),
    
    path('', views.profiles, name="profiles"),
    path('profile/home', views.index, name="home")
    


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hardware Product Recommender System-kevin -mazhura-h170289y/shop/urls.py
from . import views
from django.urls import  include
from django.urls import path,re_path as url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'shop'


urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('about/', views.about, name="about"),
    url('^', include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace="social")),
    url('product_list/', views.product_list_category, name="list"),
    url('index/', views.index, name="shophome"),
    url('Products_by_category/', views.Products_by_category, name="Products_by_category"),
    url(r'^$', views.index, name='product_list'),
    url('search/', views.search_list, name='query'),
    # url('electronics/', views.electronics, name='query'),
    url('trending/', views.search_list, name ='query'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list_category, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^cat/(?P<subcategory_slug>[-\w]+)/$', views.product_list_subcategory, name='product_list_by_subcategory'),

    url('r/reviewlist/', views.review_list, name='review_list'),
    
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    url(r'^product$', views.product_list, name='product_list'),
    
    url(r'^comparison/(?P<product_id>[0-9]+)/$', views.compare_price, name='compare_price'),
    url(r'^store/(?P<store_id>[0-9]+)/$', views.open_store, name='open_store'),
    url(r'^product/(?P<product_id>[0-9]+)/$', views.product_detail, name='product_detail'),
    url(r'^product/(?P<product_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^review/user/(?P<username>\w+)/$',views.user_review_list,name='user_review_list'),
    url(r'^review/user/$', views.user_review_list, name='user_review_list'),
    url('r/recommendation/', views.user_recommendation_list, name='user_recommendation_list'),



]

Hardware Product Recommender System-kevin -mazhura-h170289y/profiles/models.py
from unicodedata import category
from Lib.enum import auto
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from hardreco.settings import MEDIA_ROOT
from shop.models import Category

Image_default = MEDIA_ROOT + 'avatar/avatar.png'

#profile info

class Profile(models.Model):
    """Profile Model"""
    # pub_date = models.DateTimeField(default=timezone.now)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(default='', max_length=50, blank=True,null=True)
    last_name = models.CharField(default='', max_length=100, blank=True,null=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    email_verify = models.EmailField(max_length=100, blank=True, null=True)
    date_of_birth = models.DateField(max_length=12, blank=True, null=True)
    bio = models.TextField(blank=True,null=True)
    avatar = models.ImageField(blank=True,null=True, upload_to='avatar',default=Image_default)
    city = models.CharField(max_length=255, blank=True,null=True)
    district = models.CharField(max_length=255, blank=True,null=True)
    country_of_residence = models.CharField(max_length=255, blank=True,null=True)
    hobby = models.CharField(max_length=255, blank=True,null=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.first_name or self.last_name:
            self.slug = slugify("{}-{}-{}".format(self.first_name.lower(),
                                                  self.last_name.lower(), self.id))
        else:
            self.slug = slugify('profiles:profile {}'.format(self.id))
        super().save()

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('profiles:profile', args=[str(self.slug)])

    def display_bio(self):
        return mark_safe(self.bio)


class ProfileIntrests(models.Model):
    """Profile Model"""
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    intrest = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.profile.slug or self.profile.user.username:
            self.slug = slugify("{}-{}-{}".format(self.profile.slug.lower(),
                                                  self.profile.user.username.lower(), self.id))
        else:
            self.slug = slugify('ProfileIntrest:intrest {}'.format(self.id))
        super().save()

Hardware Product Recommender System-kevin -mazhura-h170289y/profiles/forms.py
from pyexpat import model
from django import forms
from django.forms import ModelForm, Textarea

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import check_password
# from bootstrap_datepicker_plus import DatePickerInput
from bootstrap_datepicker_plus.widgets import DateTimePickerInput
from zxcvbn_password.fields import PasswordField, PasswordConfirmationField
from markdownx.fields import MarkdownxFormField
from django import forms
from .models import Profile, ProfileIntrests
from django.core.validators import MinLengthValidator
from PIL import Image
class ProfForm(forms.ModelForm):
    # x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    # y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    # width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    # height = forms.FloatField(widget=forms.HiddenInput(), required=False)
    bio = MarkdownxFormField(validators=[MinLengthValidator(10)])

    class Meta:
        model = Profile
        fields = (
            "user",
            "first_name",
            "email",
            "date_of_birth",
            "bio",
            "avatar",
            "city",
            "district",
            "country_of_residence",
            "hobby",
            )
        widgets = {
            # default date-format %m/%d/%Y will be used
            'date_of_birth': DateTimePickerInput(),
        }
    def save(self):
        """Override the Save method for saving the crop photo"""
        photo = super().save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        if x is not None:
            image = Image.open(photo.avatar)
            cropped_image = image.crop((x, y, w + x, h + y))
            resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
            resized_image.save(photo.avatar.path)
        return photo

class ProfileForm(forms.ModelForm):
    """Profile Form + Fields for Photo Processing"""
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)
    bio = MarkdownxFormField(validators=[MinLengthValidator(10)])

    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'email',
            'email_verify',
            'date_of_birth',
            'bio',
            'city',
            'district',
            'country_of_residence',
            'hobby',
            'avatar',
            'x',
            'y',
            'width',
            'height',
        ]
        widgets = {
            # default date-format %m/%d/%Y will be used
            'date_of_birth': DateTimePickerInput(),
        }

    def clean(self):
        """Clean the whole form"""
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        verify = cleaned_data.get('email_verify')

        if email != verify:
            raise forms.ValidationError('Emails do not match')

    def save(self):
        """Override the Save method for saving the crop photo"""
        photo = super().save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        if x is not None:
            image = Image.open(photo.avatar)
            cropped_image = image.crop((x, y, w + x, h + y))
            resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
            resized_image.save(photo.avatar.path)
        return photo


class CustomChangePasswordForm(PasswordChangeForm):
    """Extending Password Change Form
    Overriding help_text

    """
    new_password1 = PasswordField()
    new_password2 = PasswordConfirmationField(confirm_with="new_password1")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # help_text = "<ul>" \
        #             "<li>Your password can't be too similar to " \
        #             "your other personal information</li>" \
        #             "<li>Your password must contain " \
        #             "at least 14 characters</li>" \
        #             "<li>Your password can't be a " \
        #             "commonly used password</li>" \
        #             "<li>Your password can't be " \
        #             "entirely numeric</li>" \
        #             "<li>Your password must not be " \
        #             "the same as the current password</li>" \
        #             "<li>Your password must use of " \
        #             "both uppercase and lowercase letters</li>" \
        #             "<li>Your password must include " \
        #             "of one or more numerical digits</li>" \
        #             "<li>Your password must include " \
        #             "of special characters, such as @, #, $</li>" \
        #             "</ul>"
        # self.fields['new_password1'].help_text = help_text

    class Meta:
        fields = [
            'old_password',
            'new_password1',
            'new_password2',
        ]

    def clean(self):
        """Clean is first in order not to have not matched
        error if other validation fails
        """
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if new_password1 != new_password2:
            raise forms.ValidationError('Your new password and '
                                        'confirmation do not match')

    def clean_new_password1(self):
        """Validating the Password1 Field"""
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')

        if check_password(new_password1, self.user.password):
            raise forms.ValidationError('Your password must not be '
                                        'the same as the current password')

        characters = set(new_password1)

        lower = any(letter.islower() for letter in characters)
        upper = any(letter.isupper() for letter in characters)
        digit = any(letter.isdigit() for letter in characters)

        if not upper:
            raise forms.ValidationError('Your password must use of '
                                        'both uppercase and lowercase letters')

        if not lower:
            raise forms.ValidationError('Your password must use of '
                                        'both uppercase and lowercase letters')

        if not digit:
            raise forms.ValidationError('Your password must include '
                                        'of one or more numerical digits')

        special_characters = ["@", "#", "$"]
        check = False
        for character in special_characters:
            if character in new_password1:
                check = True

        if not check:
            raise forms.ValidationError('Your password must include of '
                                        'special characters, such as @, #, $')

        first_name = self.user.profile.first_name.lower()
        last_name = self.user.profile.last_name.lower()

        if first_name in new_password1.lower():
            raise forms.ValidationError('Your password cannot be too '
                                        'similar to your other personal '
                                        'information')

        if last_name in new_password1.lower():
            raise forms.ValidationError('Your password cannot be too '
                                        'similar to your other personal '
                                        'information')

        return new_password1

class ProfileIntrestsForm(forms.ModelForm):
    
    class Meta:
        model = ProfileIntrests
        fields = ("profile",'intrest')

Hardware Product Recommender System-kevin -mazhura-h170289y/profiles/templates/profiles/change-password.html
{% extends 'shop/base.html' %}
{% load static %}

{% block css %}

    <style>
        .progress-bar-warning {
            background-color: yellow;
        }

        .progress-bar-danger {
            background-color: red;
        }

        .progress-bar-success {
            background-color: green;
        }

        .errorlist li {
            color: red;
        }
        .helptext li {
            color: green;
        }
    </style>
<link rel="stylesheet" href="{% static 'profiles/css/global.css' %}">

{% endblock %}

{% block body %}

    <h1>Change {{ profile.first_name }} {{ profile.last_name }} Password</h1>
    <form role="form" method="POST" action="">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="button" value="Save">
    </form>

{% endblock %}

Hardware Product Recommender System-kevin -mazhura-h170289y/profiles/templates/profiles/edit-profile.html
{% extends 'profiles/base.html' %}
{% load static markdown_deux_tags %}

{% block css %}

    <link rel="stylesheet" href="{% static 'profiles/cropper/cropper.min.css' %}">
  <link rel="stylesheet" href="{% static 'profiles/css/global.css' %}">

{% endblock %}

{% block body %}



    <h1>Edit {{ profile.first_name }} {{ profile.last_name }} Profile</h1>
    <form method="POST" enctype="multipart/form-data" action="" id="formUpload">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button" value="Save">
    </form>

    <!-- MODAL TO CROP THE IMAGE -->
      <div class="modal fade" id="modalCrop">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <h4 class="modal-title">Crop the photo</h4>
            </div>
            <div class="modal-body">
              <img src="" id="image" style="max-width: 100%;">
            </div>
            <div class="modal-footer">
              <div class="btn-group pull-left" role="group">
                <button type="button" class="btn btn-default js-zoom-in">
                  <span class="glyphicon glyphicon-zoom-in"></span>
                </button>
                <button type="button" class="btn btn-default js-zoom-out">
                  <span class="glyphicon glyphicon-zoom-out"></span>
                </button>
              </div>
              <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
              <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
            </div>
          </div>
        </div>
      </div>

    <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
      <div class="row" style="margin-top: 20px">
        {% for photo in photos %}
          <div class="col-sm-4 col-md-3">
            <img src="{{ photo.file.url }}" class="thumbnail">
          </div>
        {% endfor %}
      </div>



{% endblock %}


{% block js %}

    <script type="text/javascript" src="{% static 'cropper/cropper.min.js' %}"></script>

    <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_avatar").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
<script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript"
            src="{% static 'profiles/js/autogrow.js' %}"></script>
    <script type="text/javascript" src="{% static 'profiles/js/global.js' %}"></script>

    <link href="{% static 'profiles/bootstrap/css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'profiles/bootstrap/js/bootstrap.js' %}"></script>
    {{ form.media }}

{% endblock %}

Hardware Product Recommender System-kevin -mazhura-h170289y/profiles/templates/profiles/index.html
{% extends 'profiles/base.html' %}
{% load static %}
{% load static markdown_deux_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block css %}
<link href="{%static 'profiles/css/profiles.css' %}" rel="stylesheet">
  {% endblock %}
  </head>
<!-- START MAIN -->
<body>

  {% block body %}
<header>
  {% if profiles %}
        {% for profile in profiles %}
    <div class="container">
        <div class="profile">
            <div class="profile-image">
{% if profile.avatar %}
                <img src="{{ profile.avatar.url }}" alt="{{ profile.first_name }} {{ profile.last_name }}" width="80%" height="80%">
  {% endif %}
            </div>
            <div class="profile-user-settings">
              <a href="{{ profile.get_absolute_url }}">  <h5 class="profile-user-name" style="color:black; "><b>{{ profile.first_name }} {{ profile.last_name }}</b></h5></a>

          <button class="btn btn-outline-primary" >
            <a href="{% url 'profiles:edit-profile' profile.slug %}">Edit <i class="fas fa-cog" aria-hidden="true"></i></a>
          </button>
           <button class="btn btn-outline-primary"> <a href="{% url 'profiles:change-password' profile.slug %}" class="button">Change Password</a></button>


            </div>

            <div class="profile-stats">
              </h2>
              <p style="color:black">{{ profile.email }}{% if profile.city %}| {{ profile.city }} {% endif %}| {% if profile.country_of_residence %}
                         {{ profile.country_of_residence }}</p>
                    {% endif %}</p>

                <ul>
                    <li><span class="profile-stat-count">DOB:</span>{{ profile.date_of_birth }} </li>
                   {% if profile.hobby %}

                    <li><span class="profile-stat-count">Hobby:</span>  {{ profile.hobby }}</li>
                   {% endif %}
                </ul>

            </div>
            <div class="profile-bio">
              {{ profile.display_bio|markdown }}
                </p>


            </div>

        </div>
        <!-- End of profile section -->

    </div>
    <!-- End of container -->

</header>

<main>

    <div class="container">

        <div class="gallery">
        {% if product_list %}

        {% for product in product_list %}
            <a href="{% url 'shop:product_detail' product.id %}">
            <div class="gallery-item" tabindex="0">

              {{ product.name }}

                <img src="{{product.image.url}}"  class="gallery-image" alt="">

                <div class="gallery-item-info">

                    <ul>
                        <li class="gallery-item-likes"><i class="fas fa-star" aria-hidden="true"></i>{{ product.average_rating | floatformat }} average rating</li>
                        <li class="gallery-item-comments"><i class="fas fa-comment" aria-hidden="true"></i> {{ product.review_set.count }} reviews</li>
                    </ul>

                </div>

            </div>
                </a>
          {% endfor %}
          {% else %}
    <p>No products are available.</p>
{% endif %}
<div class="loader"></div>
        </div>
</body>
{% endfor %}
    {% else %}
        <p>No Profile</p>
please sign in or sign up
    {% endif %}
{% endblock %}

Hardware Product Recommender System-kevin -mazhura-h170289y/profiles/templates/profiles/new-profile.html
{% extends 'profiles/base.html' %}
{% load static markdown_deux_tags %}

{% block css %}

    <link rel="stylesheet" href="{% static 'profiles/cropper/cropper.min.css' %}">
  <link rel="stylesheet" href="{% static 'profiles/css/global.css' %}">

{% endblock %}

{% block body %}
    <h1>Add Profile</h1>
    <form style="font-size: xx-small" method="POST" enctype="multipart/form-data" action="" id="formUpload">
        {% csrf_token %}
        {% comment %} {{ form.as_table }} {% endcomment %}
        
        <table class="table">
            <tr>
              <td col-span="4">
                <label for="id_user">User:</label>
                <select name="user" required="" id="id_user">
                  {% if user %}
                    <option value="{{user.id}}" selected="">{{user}}</option>
                  {% endif %}
                </select>
              </td>
              <td col-span="4">
                <label for="id_first_name">First name:</label>
        <input type="text" name="first_name" maxlength="50" id="id_first_name">
      
              </td>
              <td col-span="4">
                <label for="id_email">Email:</label>
        <input type="email" name="email" maxlength="100" id="id_email">
      
              </td>
            </tr>
            <tr>
              <td col-span="4">
                <label for="id_date_of_birth">Date of birth:</label>
                      <div class="input-group date">
                  <input type="text" name="date_of_birth" class="form-control" id="id_date_of_birth" data-dp-config="{&quot;id&quot;: &quot;dp_1&quot;, &quot;picker_type&quot;: &quot;DATETIME&quot;, &quot;linked_to&quot;: null, &quot;options&quot;: {&quot;showClose&quot;: true, &quot;showClear&quot;: true, &quot;showTodayButton&quot;: true, &quot;format&quot;: &quot;MM/DD/YYYY HH:mm&quot;}}">
                <div class="input-group-addon input-group-append input-group-text">
                    <i class="glyphicon glyphicon-calendar"></i>
                  </div>
                </div>
              </td>
              <td col-span="4">
                <label for="id_bio">Bio:</label>
                <div class="markdownx">
              <textarea name="bio" cols="4" rows="2" required="" id="id_bio" class="markdownx-editor markdownx-editor" data-markdownx-editor-resizable="" data-markdownx-urls-path="/markdownx/markdownify/" data-markdownx-upload-urls-path="/markdownx/upload/" data-markdownx-latency="500" data-markdownx-init="" style="overflow: hidden; resize: none; height: 202px; transition: opacity 1s ease 0s;"></textarea>
          
              <div class="markdownx-preview"></div>
          </div>
              </td>
              <td col-span="4">
                <label for="id_avatar">Avatar:</label>
                <input type="file" name="avatar" accept="image/*" id="id_avatar">
              </td>
            </tr>
            <tr>
              <td col-span="4">
                <label for="id_city">City:</label>
                <input type="text" name="city" maxlength="255" id="id_city">
              </td>
              <td col-span="4">
                <label for="id_district">District:</label>
                <input type="text" name="district" maxlength="255" id="id_district">
              </td>
              <td col-span="4">
                <label for="id_country_of_residence">Country of residence:</label>
                <input type="text" name="country_of_residence" maxlength="255" id="id_country_of_residence">
                
              </td>
            </tr>
            <tr>
              <td>
                <label for="id_hobby">Hobby:</label>
                <input type="text" name="hobby" maxlength="255" id="id_hobby">
              </td>
            </tr>
        </table>
        <input type="submit" class="button" value="Save">
    </form>

    <!-- MODAL TO CROP THE IMAGE -->
      <div class="modal fade" id="modalCrop">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <h4 class="modal-title">Crop the photo</h4>
            </div>
            <div class="modal-body">
              <img src="" id="image" style="max-width: 100%;">
            </div>
            <div class="modal-footer">
              <div class="btn-group pull-left" role="group">
                <button type="button" class="btn btn-default js-zoom-in">
                  <span class="glyphicon glyphicon-zoom-in"></span>
                </button>
                <button type="button" class="btn btn-default js-zoom-out">
                  <span class="glyphicon glyphicon-zoom-out"></span>
                </button>
              </div>
              <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
              <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
            </div>
          </div>
        </div>
      </div>

    <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
      <div class="row" style="margin-top: 20px">
        {% for photo in photos %}
          <div class="col-sm-4 col-md-3">
            <img src="{{ photo.file.url }}" class="thumbnail">
          </div>
        {% endfor %}
      </div>



{% endblock %}


{% block js %}

    <script type="text/javascript" src="{% static 'cropper/cropper.min.js' %}"></script>

<script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript"
            src="{% static 'profiles/js/autogrow.js' %}"></script>
    <script type="text/javascript" src="{% static 'profiles/js/global.js' %}"></script>

    <link href="{% static 'profiles/bootstrap/css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'profiles/bootstrap/js/bootstrap.js' %}"></script>


{% endblock %}