Hardware Product Recommender System-kevin -mazhura-h170289y/app/urls.py
"""
Definition of urls for HardwareStore.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import re_path as url
from django.urls.conf import path
from django.urls import include

app_name = 'app'
urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

Hardware Product Recommender System-kevin -mazhura-h170289y/hardreco/urls.py
from django.urls import re_path as url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from shop import views as shop_views

urlpatterns = [
    path('', shop_views.index, name="mainpage"),
    path('auth', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('about/', views.about, name="about"),
    url(r'^shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('profiles/', include('profiles.urls',namespace='profiles')),
    path(r'markdownx/', include('markdownx.urls')),
    path('order/', include('order.urls',namespace='order')),
    path('tfidf/', include('tfidf.urls')),
    path('matrixfactorization/', include('matrixfactorization.urls')),
    url(r'^Scrapper/', include('scrapper.urls',namespace='scrapper')),
    url(r'^app/', include('app.urls')),
]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

Hardware Product Recommender System-kevin -mazhura-h170289y/profiles/urls.py
from . import views
from django.conf.urls import  include
from django.urls import path,re_path as url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'profiles'


urlpatterns = [
    # path('accounts/', include('profiles.accounts.urls', namespace='accounts')),
    path('profiles/<slug:profile_slug>/change-password', views.change_password, name="change-password"),
    path('profiles/<slug:profile_slug>/edit', views.edit_profile, name="edit-profile"),
    path('profiles/<slug:profile_slug>/', views.profile, name="profile"),
    path('intrest/<slug:profile_slug>/', views.add_intrest, name="add_intrest"),
    
    path('', views.profiles, name="profiles"),
    path('profile/home', views.index, name="home")
    


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hardware Product Recommender System-kevin -mazhura-h170289y/shop/urls.py
from . import views
from django.urls import  include
from django.urls import path,re_path as url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'shop'


urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('about/', views.about, name="about"),
    url('^', include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace="social")),
    url('product_list/', views.product_list_category, name="list"),
    url('index/', views.index, name="shophome"),
    url('Products_by_category/', views.Products_by_category, name="Products_by_category"),
    url(r'^$', views.index, name='product_list'),
    url('search/', views.search_list, name='query'),
    # url('electronics/', views.electronics, name='query'),
    url('trending/', views.search_list, name ='query'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list_category, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^cat/(?P<subcategory_slug>[-\w]+)/$', views.product_list_subcategory, name='product_list_by_subcategory'),

    url('r/reviewlist/', views.review_list, name='review_list'),
    
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    url(r'^product$', views.product_list, name='product_list'),
    
    url(r'^comparison/(?P<product_id>[0-9]+)/$', views.compare_price, name='compare_price'),
    url(r'^store/(?P<store_id>[0-9]+)/$', views.open_store, name='open_store'),
    url(r'^product/(?P<product_id>[0-9]+)/$', views.product_detail, name='product_detail'),
    url(r'^product/(?P<product_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^review/user/(?P<username>\w+)/$',views.user_review_list,name='user_review_list'),
    url(r'^review/user/$', views.user_review_list, name='user_review_list'),
    url('r/recommendation/', views.user_recommendation_list, name='user_recommendation_list'),



]

Hardware Product Recommender System-kevin -mazhura-h170289y/order/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput

from shop.models import Product


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product

    @property
    def amount(self):
        return (self.quantity * self.product.discount_price)


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']
        widgets = {
            'quantity': TextInput(attrs={'class': 'input', 'type': 'number', 'value': '1'}),
        }


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    surname = models.CharField(max_length=10)
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    total = models.FloatField()
    note = models.TextField(null=True, default="")
    status = models.CharField(choices=STATUS, default='New', max_length=15)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'surname', 'address', 'city', 'phone']
        widgets = {
            'name': TextInput(attrs={'class': 'input'}),
            'surname': TextInput(attrs={'class': 'input'}),
            'address': TextInput(attrs={'class': 'input'}),
            'city': TextInput(attrs={'class': 'input'}),
            'phone': TextInput(attrs={'class': 'input'}),
        }


class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # quantity = models.IntegerField()
    price = models.FloatField()
    total = models.FloatField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product

Hardware Product Recommender System-kevin -mazhura-h170289y/profiles/models.py
from unicodedata import category
from Lib.enum import auto
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from hardreco.settings import MEDIA_ROOT
from shop.models import Category

Image_default = MEDIA_ROOT + 'avatar/avatar.png'

#profile info

class Profile(models.Model):
    """Profile Model"""
    # pub_date = models.DateTimeField(default=timezone.now)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(default='', max_length=50, blank=True,null=True)
    last_name = models.CharField(default='', max_length=100, blank=True,null=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    email_verify = models.EmailField(max_length=100, blank=True, null=True)
    date_of_birth = models.DateField(max_length=12, blank=True, null=True)
    bio = models.TextField(blank=True,null=True)
    avatar = models.ImageField(blank=True,null=True, upload_to='avatar',default=Image_default)
    city = models.CharField(max_length=255, blank=True,null=True)
    district = models.CharField(max_length=255, blank=True,null=True)
    country_of_residence = models.CharField(max_length=255, blank=True,null=True)
    hobby = models.CharField(max_length=255, blank=True,null=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.first_name or self.last_name:
            self.slug = slugify("{}-{}-{}".format(self.first_name.lower(),
                                                  self.last_name.lower(), self.id))
        else:
            self.slug = slugify('profiles:profile {}'.format(self.id))
        super().save()

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse('profiles:profile', args=[str(self.slug)])

    def display_bio(self):
        return mark_safe(self.bio)


class ProfileIntrests(models.Model):
    """Profile Model"""
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    intrest = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.profile.slug or self.profile.user.username:
            self.slug = slugify("{}-{}-{}".format(self.profile.slug.lower(),
                                                  self.profile.user.username.lower(), self.id))
        else:
            self.slug = slugify('ProfileIntrest:intrest {}'.format(self.id))
        super().save()

Hardware Product Recommender System-kevin -mazhura-h170289y/shop/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from .models import Product, Review
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import check_password
# from bootstrap_datepicker_plus import DatePickerInput
from bootstrap_datepicker_plus.widgets import DateTimePickerInput
from zxcvbn_password.fields import PasswordField, PasswordConfirmationField
from markdownx.fields import MarkdownxFormField
from django import forms

from django.core.validators import MinLengthValidator
from PIL import Image


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 20, 'rows': 5}),
        }


class StoreProductForm(ModelForm):
    class Meta:
        model = Product
        fields = [
                'category',
                'subCategory',
                'name',
                'slug',
                'image',
                'description',
                'price',
                'discount_price',
                'stock',
                'image_url',
                'link'
                ]

Hardware Product Recommender System-kevin -mazhura-h170289y/profiles/views.py
from django.contrib.auth import logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required, login_required, login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from pandas import Categorical

from shop.models import Product
from .forms import ProfForm, ProfileForm, CustomChangePasswordForm, ProfileIntrestsForm
from .models import *
from shop.models import *

def index(request):
    try:
        profile = Profile.objects.get(user=request.user.id)
        if profile:
            form = ProfForm(instance=profile)
        else:
            form = ProfForm()
    except ObjectDoesNotExist:
        profile = []
        current_user = User.objects.get(id=request.user.id)
        form = ProfForm()
    # Product.objects.order_by('-name')
    product_list = []
    user = User.objects.get(id=request.user.id)
    print(user)
    return render(request, 'profiles/new-profile.html', {'myprofile': profile,'user':user,'form':form,'product_list': product_list},)
    # return HttpResponse(product_list)

def profiles(request):
    """Load Homepage via Profile Link"""
    # form = ProfileForm(user=request.user)
    try:
        profile = get_object_or_404(Profile, user=request.user.id)
        if profile:
            form = ProfileForm(instance=profile)
        else:
            form = ProfileForm()
    except ObjectDoesNotExist:
        profiles = []
    product_list = Product.objects.order_by('-name')
    return render(request, 'profiles/index.html', {'myprofile': profile,'profile_form':form,'product_list': product_list},)
@login_required
def profile(request, profile_slug):
    """Load Profile"""
    print(profile_slug)
    profile = get_object_or_404(Profile, slug=profile_slug)
    categories = Category.objects.all()
    intrest_form = ProfileIntrestsForm
    my_intrests = ProfileIntrests.objects.filter(profile=profile)
    return render(request, 'profiles/profile.html', {'profile': profile,'my_intrests':my_intrests, 'categories':categories,'intrest_form':intrest_form})
@login_required
def add_intrest(request, profile_slug):
    """Load Profile"""
    print(profile_slug)
    if request.POST:
        interest = request.POST.get('intrest')
        print(interest)
        profile = get_object_or_404(Profile, slug=profile_slug)
        categories = Category.objects.all()
        intrest_form = ProfileIntrestsForm(data=request.POST)
        my_intrests = ProfileIntrests.objects.filter(intrest=interest)
        if len(my_intrests):
            print("allready exist!!")
        else:
            if intrest_form.is_valid:
                intrest_form.save()
                my_intrests = ProfileIntrests.objects.filter(profile=profile)
        
        return render(request, 'profiles/profile.html', {'profile': profile,'my_intrests':my_intrests, 'categories':categories,'intrest_form':intrest_form})


@login_required
def edit_profile(request, profile_slug):
    """Edit Profile Form"""
    profile = get_object_or_404(Profile, slug=profile_slug)
    form = ProfileForm(instance=profile)

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, "{} {}'s profile updated."
                             .format(form.cleaned_data["first_name"],
                                     form.cleaned_data["last_name"]))
            return HttpResponseRedirect(profile.get_absolute_url())
    return render(request, "profiles/edit-profile.html", {'form': form})


@login_required
def change_password(request, profile_slug):
    """Change Password Form"""
    if request.method == 'POST':
        form = CustomChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was '
                                      'successfully updated!')
            return HttpResponseRedirect(reverse('index'))
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = CustomChangePasswordForm(request.user)
    return render(request, 'profiles/change-password.html', {
        'form': form
    })

Hardware Product Recommender System-kevin -mazhura-h170289y/shop/templates/shop/about.html
	 <h3>Categories</h3>

				 {% for c in categories %}
    <li {% if category.slug == c.slug %} {%endif %}>
        <a href ="{{ c.get_absolute_url }}">{{c.name}}</a>
        {{c.id}}
        {{c.slug}}
    </li>

	{% endfor %}

Hardware Product Recommender System-kevin -mazhura-h170289y/shop/templates/shop/list.html
{% extends 'shop/base.html' %}
{% load static %}
{% load static markdown_deux_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block css %}
<link href="{%static 'profiles/css/profiles.css' %}" rel="stylesheet">
  {% endblock %}
  </head>
<!-- START MAIN -->
<body>

  {% block body %}
<center><h1> {%if category %}{{ category.name}}{% else %}{% endif %}</h1></center>
<center><h1>{%if subcategory %}{{ subcategory.name}}{% else %}{% endif %}</h1></center>
{% for product in products %}
    <div class="container">

        <div class="gallery">
{% if product_list %}
{% for product in product_list %}
            <a href="{% url 'shop:product_detail' product.id %}">
            <div class="gallery-item" tabindex="0">

              {{ product.name }}

                <img src="{{product.image_url}}"  class="gallery-image" alt="">

                <div class="gallery-item-info">

                    <ul>
                        <li class="gallery-item-likes"><i class="fas fa-star" aria-hidden="true"></i>{{ product.average_rating | floatformat }} average rating</li>
                        <li class="gallery-item-comments"><i class="fas fa-comment" aria-hidden="true"></i> {{ product.review_set.count }} reviews</li>
                    </ul>

                </div>

            </div>
                </a>
          {% endfor %}
          {% else %}
    <p>No products are available.</p>
{% endif %}
<div class="loader"></div>
        </div>
    </div>
</body>
{% endfor %}

{% endblock %}

Hardware Product Recommender System-kevin -mazhura-h170289y/shop/templates/shop/product_compare.html
{% extends 'shop/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" >
{% block body %}
<body>
{% if request.GET.q %}
   <div class='col-12 mb-3'>
    <u> <center> <h1>Result for {{request.GET.q}}</h1> </center></u>
   </div>
    {% else %}
    <div>search bar</div>
    {% endif %}
    <h1></h1>
    <div class="row">
       {{product}}
        {% if product %}
        <a href="{{product.get_absolute_url }}">
        <div class="col-md-3">
            <div class="product-grid2">
                <div class="product-image2">
                    <a href="#">
                        <img class="pic-1" src="{{ product.image_url }}">
                        <img class="pic-2" src="{{ product.image_url }}">
                    </a>
                    <ul class="social">
                        <li><a href="#" data-tip="Quick View"><i class="fa fa-eye"></i></a></li>
                        <li><a href="#" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                        <li><a href="#" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                    </ul>
                    <a class="add-to-cart" href="">Add to cart</a>
                </div>
                <div class="product-content">
                    <h3 class="title">
                        <a href="{% url 'shop:product_detail' product.id %}">{{product.name }}</a></h3>
                    <span class="price">ZWL {{product.price}}</span>
                    <a href="{% url 'shop:compare_price' product.id %}">Price Comparison</a>
                </div>
            </div>

        </div>
        {% endif %}
    </div>
    <hr/>
    {% comment %} <h2>Recommendation Product List</h2>
    <hr/>
    <div class="container">
        {% if online_products %}
        
        <table class="table"> 
            <thead>
                <tr>
                    <th>Product</td>
                    <th>Store</td>
                    <th>Image</td>
                    <th>Price</td>
                </tr>
            </thead>
            <tbody>
            {% for product in online_products%}
            <tr>
                <td>{{product.description}}</td>
                <td> <img class="pic-1"src="{{ MEDIA_URL }}/{{product.store.image}}" height="20px" width="30px"/>{{product.store}}</td>
                <td> <img class="pic-1"src="{{ MEDIA_URL }}/{{product.image}}" height="60px" width="70px"/></td>
                <td> <img class="pic-1"src="{{product.online_image_url}}" height="60px" width="70px"/></td>
                <td>{{product.price}}</td>
            </tr>
        
            {% endfor %}</tbody>
        </table>
        {% endif %}

    </div> {% endcomment %}
    <div class="row">
        <h2>Other Related Products</h2>
        {% if sugested_products %}
        
            {% for product in sugested_products %}
                <a href="{{ product.get_absolute_url }}">
                    <div class="col-md-3 col-sm-6">
                        <div class="product-grid2">
                            <div class="product-image2">
                                <a href="#">
                                    <img class="pic-1" src="{{ product.image_url }}">
                                    <img class="pic-2" src="{{ product.image_url }}">
                                </a>
                                <ul class="social">
                                    <li><a href="#" data-tip="Quick View"><i class="fa fa-eye"></i></a></li>
                                    <li><a href="#" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                                    <li><a href="#" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                                </ul>
                                <a class="add-to-cart" href="">Add to cart</a>
                            </div>
                            <div class="product-content">
                                
                                <span class="price">{{ product.name }}</span><br/>
                                <span class="price">ZWL {{ product.price }}</span>

                                <a href="{% url 'shop:compare_price' product.id %}">Price Comparison</a>
                            </div>
                        </div>

                    </div>
               
            {% endfor %}
        {% endif %}

    </div>
            {% endblock %}

           
        </body>
</html>

Hardware Product Recommender System-kevin -mazhura-h170289y/shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
 {% block css %}
 {% load bootstrap_icons %}
<link href="{% static 'shop/css/productdetail.css' %}" rel="stylesheet" type="text/css" media="all" />
{% endblock %}
{% block body %}
<!-- page -->
<main>
  <div class="container">
    <div class="grid second-nav">
      <div class="column-xs-12">
        <nav>
          <ol class="breadcrumb-list">
            <li class="breadcrumb-item"><a href="#">Product</a></li>
            <li class="breadcrumb-item"><a href="#">{{product.category}}</a></li>
            <li class="breadcrumb-item active"> {{product.subcategory}}</li>
          </ol>
        </nav>
      </div>
    </div>
    <div class="grid product">
      <div class="column-xs-12 column-md-7">
        <div class="product-gallery">
          <div class="product-image">
            <img class="active" src="{{product.image_url}}">
          </div>
          <ul class="image-list">
            <li class="image-item"><img src="{{product.image_url}}"></li>
            <li class="image-item"><img src="{{product.image_url}}"></li>
            <li class="image-item"><img src="{{product.image_url}}"></li>
          </ul>
        </div>
      </div>
      <div class="column-xs-12 column-md-5">
        <h1>{{product.name}}</h1>
        <h4>Price: <del>$ {{product.price}}</del> ${{product.discount_price}}</h4>
        <div class="description">
          <p style="color:black;">{{product.description}}</p>
            <p style="color:black;">Total reviews:{{ product.review_set.count }} reviews </p>
            <p style="color:black;"> Average rating: {{ product.average_rating | floatformat }} average rating</p>
			<p style="color:black;">Last updated: {{product.updated}}</p>
          <p style="color:black;">Available stock: {{product.stock}} only</p>
        </div>
            <div class="product-btns">

                <form action="/order/addtocart/{{ product.id }}" method="post">
                    {% csrf_token %}
                    <div class="qty-input">
                        <input type="number" name="quantity" id="id_quantity" value="1" min="1" max="{{product.stock}}" class="input">
                    </div>
                    <input type="submit" class="add-to-cart" value="Add to Cart">
                </form>

            </div>

      </div>
    </div>
    <div class="grid related-products">
      <div class="column-xs-12">
        <h3>You may also like : <i style="font-size:x-small" class="success">Recomendation</i></h3>
      </div>
      {% if online_products %}
      {% for product in online_products %}
      <div class="column-xs-12 column-md-4">
        <img src="{{ MEDIA_URL }}/{{product.image}}" height="60px" width="70px">
        <img src="{{product.online_image_url}}" height="60px" width="70px">
        <h4>{{product.description}}</h4>
        <h5>{{product.store}}</h5>


        <p class="price">{{product.price}}</p>
        <hr/>
        <img src="{{ MEDIA_URL }}/{{product.store.image}}" height="60px" width="70px">
      </div>
      {% endfor %}
      {% endif %}
    </div>

    </div>
  </div>
</main>



{% if product.review_set.all %}
	<div class="comments-container">
		<h1>Recent reviews </h1>
		{% for review in product.review_set.all %}
		<ul id="comments-list" class="comments-list">
			<li>
				<div class="comment-main-level">
					<!-- Avatar -->
					<div class="comment-avatar">
            {% comment %} <img src="{% static 'img/s.png' %}" alt=""> {% endcomment %}
            {% bs_icon 'person' %}
          </div>
					<!-- Contenedor del Comentario -->
					<div class="comment-box">
						<div class="comment-head">
							<h6 class="comment-name by-author">{{ review.user_name}}</h6>
							<span>{{review.pub_date}}</span>
							<i class="fa fa-reply"></i>
							<i class="fa fa-heart"></i>
						</div>
						<div class="comment-content"><b>Rated {{ review.rating }} of 5 by {{ review.user_name }}</b></div>
						<div class="comment-content">
							{{ review.comment }}
						</div>
						<a href="{% url 'shop:review_detail' review.id %}">
                Read more
            </a>
					</div>
				</div>
			</li>
		</ul>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this product yet</p>
{% endif %}


<div class="comments-container">
	<h1>Add your review</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'shop:add_review' product.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}

    {% buttons %}

    <button type="submit" class="btn btn-primary">
      {% bs_icon 'star' %}
      {% comment %} {% bootstrap_icon "star" %} {% endcomment %}
       Rate this product
    </button>
    {% endbuttons %}
</form>
{% endblock %}

</div>

Hardware Product Recommender System-kevin -mazhura-h170289y/shop/templates/shop/review_detail.html
{% block title %}
<h2><a href="{% url 'shop:product_detail' review.product.id %}">{{ review.product.name }}</a></h2>
{% endblock %}

{% block content %}
<h4>Rated {{ review.rating }} of 5 by <a href="{% url 'shop:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h4>
<p>{{ review.pub_date }}</p>
<p>{{ review.comment }}</p>
{% endblock %}

Hardware Product Recommender System-kevin -mazhura-h170289y/shop/templates/shop/review_list.html
{% block title %}
<h2>Latest reviews</h2>
{% endblock %}

{% block content %}
{% if latest_review_list %}
<div class="row">
    {% for review in latest_review_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'shop:review_detail' review.id %}">
        {{ review.product.name }}
        </a></h4>
        <h6>Rated {{ review.rating }} of 5 by <a href="{% url 'shop:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h6>
        <p>{{ review.comment }}</p>
        review.id
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

Hardware Product Recommender System-kevin -mazhura-h170289y/shop/templates/shop/trending.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="col-10 agileits_search">
<form class="form-inline" action='{% url "shop:query" %}' method="GET">
	<input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" required>
	<button class="btn my-2 my-sm-0" type="submit">Search</button>
</form>
</div>

</body>
</html>